name: Upload to ECR
on:
  workflow_dispatch:

jobs:
  upload-to-ecr:
    name: Upload Docker Image to ECR using Pulumi
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-tags: true

      - name: Get version from tag
        id: get_version
        run: |
          if [[ "${{ github.ref_type }}" == "tag" ]]; then
            echo "VERSION=${{ github.ref_name }}" >> $GITHUB_OUTPUT
          else
            VERSION=$(git describe --tags --abbrev=0)
            echo "VERSION=$VERSION" >> $GITHUB_OUTPUT
          fi
          echo "Resolved version: ${{ github.ref_type == 'tag' && github.ref_name || '$(git describe --tags --abbrev=0)' }}"

      - name: Print resolved version
        run: echo "Will tag ECR image with version -> ${{ steps.get_version.outputs.VERSION }}"

      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-region: ${{ secrets.AWS_REGION }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: Install Node.js dependencies for Pulumi project
        run: npm install
        working-directory: deployment/ecrImage/

      - name: Run Pulumi Up
        uses: pulumi/actions@v6
        with:
          command: up
          stack-name: dmnd-tech-org/dmnd-client-image/dmnd-client-image
          work-dir: deployment/ecrImage/
          config: version=${{ steps.get_version.outputs.VERSION }}
        env:
          PULUMI_ACCESS_TOKEN: ${{ secrets.PULUMI_ACCESS_TOKEN }}
